name: zaker
description: "نظام ذاكر المحسن - نظام متقدم لاستخراج وتحليل النصوص التعليمية بالذكاء الاصطناعي"
version: 2.1.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # === المكتبات الأساسية للتطبيق ===
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  
  # === مكتبات الذكاء الاصطناعي ===
  google_generative_ai: ^0.4.3
  
  # === مكتبات استخراج النصوص ===
  syncfusion_flutter_pdf: ^31.1.19
  
  # === مكتبات اختيار الملفات ===
  file_picker: ^10.3.3
  image_picker: ^1.0.4
  
  
  # === مكتبات قاعدة البيانات والتخزين ===
  sqflite: ^2.3.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.1
  
  # === مكتبات الواجهة والتصميم ===
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  percent_indicator: ^4.2.5
  uuid: ^4.5.1
  flutter_card_swiper: ^7.0.2
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - logo.png
    - assets/animations/

flutter_icons:
  android: true
  ios: true
  image_path: "logo.png"