name: zaker
description: "تطبيق دراسي لتلخيص ملفات PDF وإنشاء بطاقات تعليمية واختبارات."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # تمت الإضافة لدعم اللغة العربية
    sdk: flutter

  # flutter_markdown: ^0.7.1
  # Icons
  syncfusion_flutter_pdf: ^31.1.20 # --- تم التغيير: مكتبة احترافية لاستخراج النصوص من PDF ---

  provider: ^6.1.2 # لإدارة الحالة
  google_generative_ai: ^0.4.1 # للذكاء الاصطناعي
  supabase_flutter: ^2.5.0 # لتخزين الملفات (اختياري)
  file_picker: ^8.0.3 # لاختيار الملفات
  image_picker: ^1.1.2 # لاختيار الصور من المعرض
  shared_preferences: ^2.2.3 # للتخزين المحلي
  flutter_markdown: ^0.7.1 # لعرض الملخصات
  percent_indicator: ^4.2.3 # لعرض شريط التقدم
  flutter_card_swiper: ^7.0.1 # لعرض البطاقات التعليمية
  lottie: ^3.1.2 # لعرض الأنيميشن
  path_provider: ^2.1.3 # للوصول لمسارات الملفات
  pdfx: ^2.6.0 # مكتبة جديدة وقوية لاستخراج النصوص من PDF

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  google_fonts:

flutter:
  uses-material-design: true
  assets:
    - logo.png
    - assets/animations/

flutter_icons:
  android: true
  ios: true
  image_path: "logo.png"